version: '3.8'

services:
  cinematic-flux:
    build: .
    container_name: cinematic-flux
    ports:
      - "5000:5000"
    volumes:
      # Map your host downloads folder to the container's downloads
      - ./downloads:/app/downloads
      
      # Example: Map directly to a USB Flash Drive (Linux)
      # - /media/puser/USB_DRIVE:/app/downloads
    environment:
      - FLUX_DOWNLOAD_PATH=/app/downloads
    restart: unless-stopped
